fix: include `pg-format/lib/reserved.js` in `pkg` `assets`
Fixes:

```
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: Cannot find module '/snapshot/storage-api/node_modules/pg-format/lib/reserved.js'
Require stack:
- /snapshot/storage-api/node_modules/pg-format/lib/index.js
- /snapshot/storage-api/node_modules/pg-listen/dist/index.js
- /snapshot/storage-api/node_modules/pg-listen/index.js
- /snapshot/storage-api/dist/utils/tenant.js
- /snapshot/storage-api/dist/plugins/postgrest.js
- /snapshot/storage-api/dist/routes/bucket/index.js
- /snapshot/storage-api/dist/app.js
- /snapshot/storage-api/dist/server.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/snapshot/storage-api/node_modules/pg-format/lib/index.js:4:19)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/storage-api/node_modules/pg-format/lib/index.js',
    '/snapshot/storage-api/node_modules/pg-listen/dist/index.js',
    '/snapshot/storage-api/node_modules/pg-listen/index.js',
    '/snapshot/storage-api/dist/utils/tenant.js',
    '/snapshot/storage-api/dist/plugins/postgrest.js',
    '/snapshot/storage-api/dist/routes/bucket/index.js',
    '/snapshot/storage-api/dist/app.js',
    '/snapshot/storage-api/dist/server.js'
  ],
  pkg: true
}
```